// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr_rkPBXHjzjqqaXxgLriIDGE7btzhJlI',
    appId: '1:985637539448:web:865e3eaffdef7e2efce78d',
    messagingSenderId: '985637539448',
    projectId: 'chat-app-431df',
    authDomain: 'chat-app-431df.firebaseapp.com',
    storageBucket: 'chat-app-431df.appspot.com',
    measurementId: 'G-ZX0DBLD4T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBegRiWwzzBeNH1VxYQlbs29LjKzPjL9hk',
    appId: '1:985637539448:android:2747a37f037a6e90fce78d',
    messagingSenderId: '985637539448',
    projectId: 'chat-app-431df',
    storageBucket: 'chat-app-431df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbcBEYW-RuS4XZg9lTwvRzBFmfVlqJKcU',
    appId: '1:985637539448:ios:c6b38078698715a1fce78d',
    messagingSenderId: '985637539448',
    projectId: 'chat-app-431df',
    storageBucket: 'chat-app-431df.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbcBEYW-RuS4XZg9lTwvRzBFmfVlqJKcU',
    appId: '1:985637539448:ios:e349f3b4082b6863fce78d',
    messagingSenderId: '985637539448',
    projectId: 'chat-app-431df',
    storageBucket: 'chat-app-431df.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
